'use client'
import Link from 'next/link'
import { Check, Eye, MoreHorizontal, Paperclip, Search, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { Ticket } from '@/types'
import { LABELS } from '@/lib/constants'
import { format } from 'date-fns'
import { es } from 'date-fns/locale'
import toast from 'react-hot-toast'

export function TicketTable({tickets,onRefresh,compact=false}:{tickets:Ticket[];onRefresh:()=>void;compact?:boolean}){
 const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [priority,setPriority]=useState('');const [status,setStatus]=useState('');const [special,setSpecial]=useState('')
 const filtered=useMemo(()=>tickets.filter(t=>{const q=query.toLowerCase(); return (!q||`${t.id} ${t.title} ${t.description} ${t.clientProject||''} ${t.assignedTo?.name||''}`.toLowerCase().includes(q))&&(!category||t.category===category)&&(!priority||t.priority===priority)&&(!status||t.status===status)&&(!special||(special==='overdue'?new Date(t.dueAt)<new Date()&&!['COMPLETED','CANCELLED'].includes(t.status):t.attachments.length>0))}),[tickets,query,category,priority,status,special])
 async function patch(id:number,data:object){const r=await fetch(`/api/tickets/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)return toast.error('No se pudo actualizar.');toast.success('Ticket actualizado.');onRefresh()}
 async function remove(id:number){if(!confirm('¿Eliminar este ticket? Quedará registrado en el historial.'))return;const r=await fetch(`/api/tickets/${id}?actorId=1`,{method:'DELETE'});if(r.ok){toast.success('Ticket eliminado.');onRefresh()}}
 return <div className="panel"><div className="toolbar"><div className="search"><Search/><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por título, cliente, responsable o ID…" aria-label="Buscar tickets"/></div>{!compact&&<><select className="input filter" value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filtrar categoría"><option value="">Categorías</option><option value="SUPPORT">Soporte</option><option value="GOOGLE_ADS">Google Ads</option><option value="WEBSITE">Sitio web</option></select><select className="input filter" value={priority} onChange={e=>setPriority(e.target.value)} aria-label="Filtrar prioridad"><option value="">Prioridades</option>{['LOW','MEDIUM','HIGH','URGENT'].map(x=><option value={x} key={x}>{LABELS[x]}</option>)}</select><select className="input filter" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filtrar estado"><option value="">Estados</option>{['NEW','PENDING','IN_PROGRESS','IN_REVIEW','COMPLETED','CANCELLED'].map(x=><option value={x} key={x}>{LABELS[x]}</option>)}</select><select className="input filter" value={special} onChange={e=>setSpecial(e.target.value)} aria-label="Filtros especiales"><option value="">Todos</option><option value="overdue">Vencidos</option><option value="files">Con archivos</option></select></>}</div>
 <div className="table-wrap"><table className="table"><thead><tr><th>ID / Ticket</th><th>Categoría</th><th>Prioridad</th><th>Estado</th><th>Cliente / proyecto</th><th>Responsable</th><th>Vencimiento</th><th>Archivos</th>{!compact&&<><th>Creado</th><th>Actualizado</th></>}<th>Acciones</th></tr></thead><tbody>{filtered.map(t=>{const overdue=new Date(t.dueAt)<new Date()&&!['COMPLETED','CANCELLED'].includes(t.status);return <tr key={t.id}><td><span className="subtle">TF-{String(t.id).padStart(4,'0')}</span><br/><Link className="ticket-link" href={`/tickets/${t.id}`}>{t.title}</Link></td><td><span className="category"><i className={`dot dot-${t.category.toLowerCase()}`}/>{LABELS[t.category]}</span></td><td><span className={`badge badge-${t.priority.toLowerCase()}`}>{LABELS[t.priority]}</span></td><td><select className={`badge badge-${t.status.toLowerCase()}`} value={t.status} onChange={e=>patch(t.id,{status:e.target.value,actorId:1})} style={{border:0}} aria-label={`Estado de ${t.title}`}>{['NEW','PENDING','IN_PROGRESS','IN_REVIEW','COMPLETED','CANCELLED'].map(x=><option key={x} value={x}>{LABELS[x]}</option>)}</select></td><td>{t.clientProject||<span className="subtle">Sin especificar</span>}</td><td>{t.assignedTo?.name||<span className="subtle">Sin asignar</span>}</td><td className={overdue?'overdue':''}>{format(new Date(t.dueAt),'dd MMM, h:mm a',{locale:es})}</td><td>{t.attachments.length?<span className="category"><Paperclip size={15}/>{t.attachments.length}</span>:'—'}</td>{!compact&&<><td className="subtle">{format(new Date(t.createdAt),'dd/MM/yy')}</td><td className="subtle">{format(new Date(t.updatedAt),'dd/MM/yy h:mm a')}</td></>}<td><div className="row-actions"><Link href={`/tickets/${t.id}`} className="btn btn-ghost btn-icon" aria-label="Ver ticket"><Eye size={17}/></Link><button onClick={()=>patch(t.id,{status:'COMPLETED',actorId:1})} className="btn btn-ghost btn-icon" aria-label="Marcar completado"><Check size={17}/></button><button onClick={()=>remove(t.id)} className="btn btn-ghost btn-icon" aria-label="Eliminar ticket"><Trash2 size={16}/></button></div></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty"><MoreHorizontal/><div>No hay tickets que coincidan con los filtros.</div></div>}</div></div>
}
