'use client'
import { useCallback,useEffect,useState } from 'react'
import { DragDropContext,Droppable,Draggable,DropResult } from '@hello-pangea/dnd'
import Link from 'next/link'
import { CalendarClock, Paperclip, Plus } from 'lucide-react'
import { format } from 'date-fns'
import { es } from 'date-fns/locale'
import type { Ticket } from '@/types'
import { LABELS } from '@/lib/constants'
import toast from 'react-hot-toast'
const columns=['NEW','PENDING','IN_PROGRESS','IN_REVIEW','COMPLETED']
export default function KanbanPage(){const [tickets,setTickets]=useState<Ticket[]>([]);const load=useCallback(()=>fetch('/api/tickets').then(r=>r.json()).then(setTickets),[]);useEffect(()=>{load()},[load]);async function drag(result:DropResult){if(!result.destination||result.destination.droppableId===result.source.droppableId)return;setTickets(ts=>ts.map(t=>t.id===Number(result.draggableId)?{...t,status:result.destination!.droppableId}:t));const r=await fetch(`/api/tickets/${result.draggableId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:result.destination.droppableId,actorId:1})});if(!r.ok){toast.error('No se pudo cambiar el estado.');load()}else toast.success('Estado actualizado.')}return <><div className="page-head"><div><h2>Tablero Kanban</h2><p>Arrastra tickets entre columnas para actualizar su estado.</p></div><Link href="/tickets/new" className="btn btn-primary"><Plus size={17}/>Crear ticket</Link></div><DragDropContext onDragEnd={drag}><div className="kanban">{columns.map(status=>{const list=tickets.filter(t=>t.status===status);return <div className="kanban-col" key={status}><div className="kanban-head"><span>{LABELS[status]}</span><span>{list.length}</span></div><Droppable droppableId={status}>{provided=><div className="kanban-list" ref={provided.innerRef} {...provided.droppableProps}>{list.map((t,index)=>{const overdue=new Date(t.dueAt)<new Date()&&t.status!=='COMPLETED';return <Draggable draggableId={String(t.id)} index={index} key={t.id}>{p=><article ref={p.innerRef} {...p.draggableProps} {...p.dragHandleProps} className={`kanban-card ${overdue?'is-overdue':''}`}><Link href={`/tickets/${t.id}`}>{t.title}</Link><span className={`badge badge-${t.priority.toLowerCase()}`}>{LABELS[t.priority]}</span><div className="subtle" style={{marginTop:10}}><span className="category"><i className={`dot dot-${t.category.toLowerCase()}`}/>{LABELS[t.category]}</span></div><div className="kanban-meta"><span className={overdue?'overdue':''}><CalendarClock size={13}/> {format(new Date(t.dueAt),'dd MMM, h:mm a',{locale:es})}</span>{t.attachments.length>0&&<span><Paperclip size={13}/> {t.attachments.length}</span>}</div><div className="kanban-meta"><span>{t.assignedTo?.name||'Sin asignar'}</span><span>TF-{String(t.id).padStart(4,'0')}</span></div></article>}</Draggable>})}{provided.placeholder}</div>}</Droppable></div>})}</div></DragDropContext></>}
